FROM mcr.microsoft.com/windows/servercore:1809 as core
FROM mcr.microsoft.com/windows/nanoserver:1809
COPY --from=core /windows/system32/netapi32.dll /windows/system32/
COPY manifest-tool manifest-tool.exe
ENTRYPOINT [ "manifest-tool.exe" ]
